# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 67f88d5456b872402a96ec67f50fe7c8a273fbf4a795dcea83d63eb3dee5b68730f16391383d33ea338f4eed036cb30f6f0fd6d7807154a33b3e41cf57f49aa4

test:
  secret_key_base: 9048dc31da66f0408ed5be4fd08e5184fd0f5eb0f180bbacbde0d4d93b25562ae1b0539945cabe7f71612c9bf74670256281e01879f09cc2c61fd298b77215a3

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
